[package]
name = "pyo3-polars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = {version = "*", default_features=false}
polars-core = {version = "*", default_features=false}
pyo3 = "0.17"
thiserror = "1"
arrow2 = "*"